<a href="https://colab.research.google.com/github/sjohn214/Colab-Repos/blob/IMDB/Second_NN_IMDB_BinClass_SLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Second Neural Network Model

#### I) Why is the training loss lower than validation loss? The training loss is almost always lower than the validation loss because the model is actively optimizing its weights using only the training dataset

#### II) Why is training accuracy higher than evaluation or test accuracy? Training accuracy is higher because the model has built its decision boundaries to perfectly fit the training examples.

In [4]:
# import IMDB Data Set

from tensorflow.keras.datasets import imdb
(training_data, training_labels), (test_data, test_labels) = imdb.load_data(num_words=1000)

17464789/17464789 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [ ]:
# training_data
# Why is that?
# Convert characters into numbers
# uni-dimensional and multi-dimensional
# Numpy library arrays in tensorflow
# what are tensors?


In [5]:
# reverse coding to get the words back from the integers

word_index = imdb.get_word_index()

reverse_word_index = dict(
    [(value, key) for (key, value) in word_index.items()])

decoded_review = " ".join(
    [reverse_word_index.get(i-3, "?") for i in training_data[0]])

print(decoded_review)

1641221/1641221 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step
? this film was just brilliant casting ? ? story direction ? really ? the part they played and you could just imagine being there robert ? is an amazing actor and now the same being director ? father came from the same ? ? as myself so i loved the fact there was a real ? with this film the ? ? throughout the film were great it was just brilliant so much that i ? the film as soon as it was released for ? and would recommend it to everyone to watch and the ? ? was amazing really ? at the end it was so sad and you know what they say if you ? at a film it must have been good and this definitely was also ? to the two little ? that played the ? of ? and paul they were just brilliant children are often left out of the ? ? i think because the stars that play them all ? up are such a big ? for the whole film but these children are amazing and should be ? for what they have done don't you think the whole story was so ? because it was true and was 

In [6]:
# reverse coding to get the words back from the integers

word_index = imdb.get_word_index()

reverse_word_index = dict(
    [(value, key) for (key, value) in word_index.items()])

decoded_review = " ".join(
    [reverse_word_index.get(i-3, "?") for i in training_data[8]])

print(decoded_review)

? just got out and cannot believe what a brilliant documentary this is ? do you ? out of a movie theater in such ? and ? ? movies have become so over ? that the ? of ? something truly special and unique ? happens ? ? did this to me when it first came out and this movie is doing to me now i didn't know a thing about this before going into it and what a surprise if you hear the ? you might get the feeling that this is one of those ? movies about an amazing ? ? with over the top music and trying to have us ? ? of what a great story it is telling but then not ? us in ? this is not that movie the people tell the story this does such a good job of ? every moment of their ? while we ? their world and feel every second with them there is so much beyond the ? that makes everything they go through so much more ? ? the ? was also a great ? about ? ? and showing the ? in an ? way but this film is much more of a human story i just saw it today but i will go and say that this is one of the best ? i 

# Step II) Vectorize the training_data

In [7]:
# NN models cannot deal with integer values directly.

import numpy as np
def vectorize_sequences(sequences, dimensions=10000):
  results = np.zeros((len(sequences), dimensions))
  for i, sequence in enumerate(sequences):
    for j in sequence:
      results[i, j] = 1.
      return results

x_train = vectorize_sequences(training_data)
x_test = vectorize_sequences(test_data)

x_train[8]

array([0., 0., 0., ..., 0., 0., 0.])

# Step III) Vectorize labels

In [8]:
training_labels

array([1, 0, 0, ..., 0, 1, 0])

In [9]:
test_labels

array([0, 1, 1, ..., 0, 0, 0])

In [12]:
y_train = np.array(training_labels).astype("float32")

y_test = np.array(test_labels).astype("float32")
y_train


array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)